#!/usr/bin/env python3
"""First-run setup wizard for protoArtoo.

Writes user.mk at the repository root with build configuration
overrides for OTA IP, USB upload port, and audio backend selection.

Usage:
    make setup                   via Makefile
    python3 tools/configure.py   direct invocation

questionary is used for interactive prompts when installed.
Falls back to plain input() on a fresh system — no pip install required.
Install optional deps: pip install -r tools/requirements.txt
"""
from __future__ import annotations

import os
import sys

# ---------------------------------------------------------------------------
# Repository layout
# ---------------------------------------------------------------------------

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
USER_MK_PATH = os.path.join(REPO_ROOT, "user.mk")

# ---------------------------------------------------------------------------
# Build options
# ---------------------------------------------------------------------------

DEFAULTS = {
    "OTA_IP": "10.0.0.22",
    "BUILD_ENV": "protoArtoo",
    "UPLOAD_PORT": "/dev/ttyUSB0",
}

# (display label, BUILD_ENV value)
AUDIO_BACKENDS = [
    ("DY-SV5W (default — confirmed hardware)", "protoArtoo"),
    ("CHIRP", "protoArtoo_chirp"),
    ("MP3 Trigger", "protoArtoo_mp3trigger"),
]

# ---------------------------------------------------------------------------
# questionary — optional; stdlib fallback when absent
# ---------------------------------------------------------------------------

try:
    import questionary as _q
    _HAS_Q = True
except ImportError:
    _q = None  # type: ignore[assignment]
    _HAS_Q = False


def _select(message: str, choices: list, default: str) -> str | None:
    """Prompt the user to pick from a list. Returns None on cancellation."""
    if _HAS_Q:
        return _q.select(message, choices=choices, default=default).ask()
    print(message)
    for i, choice in enumerate(choices, 1):
        marker = " (default)" if choice == default else ""
        print(f"  {i}) {choice}{marker}")
    raw = input(f"Select [1-{len(choices)}] (Enter for default): ").strip()
    if not raw:
        return default
    if raw.isdigit() and 1 <= int(raw) <= len(choices):
        return choices[int(raw) - 1]
    return default


def _text(message: str, default: str) -> str | None:
    """Free-text prompt with default. Returns None on cancellation."""
    if _HAS_Q:
        return _q.text(message, default=default).ask()
    raw = input(f"{message} [{default}]: ").strip()
    return raw or default


def _confirm(message: str, default: bool = True) -> bool | None:
    """Yes/no prompt. Returns None on cancellation."""
    if _HAS_Q:
        return _q.confirm(message, default=default).ask()
    hint = "Y/n" if default else "y/N"
    raw = input(f"{message} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw.startswith("y")


# ---------------------------------------------------------------------------
# user.mk helpers
# ---------------------------------------------------------------------------

def _read_user_mk() -> dict:
    """Parse key=value pairs from user.mk. Returns empty dict if absent."""
    result = {}
    try:
        with open(USER_MK_PATH) as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, _, val = line.partition("=")
                    result[key.strip()] = val.strip()
    except OSError:
        pass
    return result


def _render_user_mk(ota_ip: str, build_env: str, upload_port: str) -> str:
    return (
        "# user.mk — generated by tools/configure.py; do not commit\n"
        f"OTA_IP      = {ota_ip}\n"
        f"BUILD_ENV   = {build_env}\n"
        f"UPLOAD_PORT = {upload_port}\n"
    )


# ---------------------------------------------------------------------------
# Wizard entry point
# ---------------------------------------------------------------------------

def run() -> int:
    """Run the setup wizard. Returns process exit code."""

    # --- Warn if questionary is missing ---
    if not _HAS_Q:
        print("Note: questionary not installed — using plain prompts.")
        print("      Run 'pip install -r tools/requirements.txt' for a nicer experience.")
        print()

    # --- Check for existing user.mk ---
    existing = _read_user_mk()
    if existing:
        print("user.mk already exists with current settings:")
        for k, v in existing.items():
            print(f"  {k} = {v}")
        print()
        overwrite = _confirm("Overwrite?", default=True)
        if overwrite is None or not overwrite:
            print("Cancelled. user.mk unchanged.")
            return 1
        print()

    # --- Q1: Audio backend ---
    audio_labels = [label for label, _ in AUDIO_BACKENDS]
    default_build_env = existing.get("BUILD_ENV", DEFAULTS["BUILD_ENV"])
    default_label = next(
        (label for label, env in AUDIO_BACKENDS if env == default_build_env),
        audio_labels[0],
    )
    chosen_label = _select("Audio backend:", audio_labels, default=default_label)
    if chosen_label is None:
        print("\nCancelled.")
        return 1
    build_env = dict(AUDIO_BACKENDS)[chosen_label]

    # --- Q2: OTA IP ---
    ota_ip = _text(
        "OTA target IP address:",
        default=existing.get("OTA_IP", DEFAULTS["OTA_IP"]),
    )
    if ota_ip is None:
        print("\nCancelled.")
        return 1

    # --- Q3: USB upload port ---
    upload_port = _text(
        "USB upload port:",
        default=existing.get("UPLOAD_PORT", DEFAULTS["UPLOAD_PORT"]),
    )
    if upload_port is None:
        print("\nCancelled.")
        return 1

    # --- Q4: Confirm and write ---
    content = _render_user_mk(ota_ip, build_env, upload_port)
    print()
    print("Will write user.mk:")
    print()
    for line in content.splitlines():
        print(f"  {line}")
    print()
    print(
        "Note: user.mk is gitignored. "
        "Re-run 'make setup' to change settings at any time."
    )
    print()

    confirmed = _confirm("Write user.mk?", default=True)
    if confirmed is None or not confirmed:
        print("Cancelled.")
        return 1

    try:
        with open(USER_MK_PATH, "w") as fh:
            fh.write(content)
    except OSError as exc:
        print(f"Error writing {USER_MK_PATH}: {exc}", file=sys.stderr)
        return 1

    print()
    print(f"Written: {USER_MK_PATH}")
    print("Run 'make help' to see all available commands.")
    return 0


if __name__ == "__main__":
    sys.exit(run())
