#!/usr/bin/env python3
"""Generate the Component Registry manifest from docs/products.yaml.

docs/products.yaml is the one declaration of every Component Family and every
product in it. The firmware never reads it: it compiles the X-macro manifest
this writes, and every firmware table, the identity payload and the operator
lineup expand that manifest (ADR 0042 as amended 2026-09-09).

    docs/products.yaml
       '-> include/component_registry.inc   the PA_COMPONENT_CATEGORY and
                                            PA_COMPONENT_PART rows

The manifest's long header - what each macro column means and why - is the
generated file's own contract, so it is written here, once, and lands at the
top of every output. The prose that explains a family or a row lives with the
row it explains, in the YAML (`comment`, `section`, `confirmed_source`), and is
written out as the `//` lines above that row.

LAYOUT. Rows are aligned per family: every column of a family's rows is padded
to that family's widest value, so a reader scans a column straight down. A
product that declares capabilities spans lines - its first line ends at the
confirmed word, its capability bits follow two to a line, and its gate and
`included` close it - because an `AudioDriver::AUDIO_CAP_*` word is too long
to sit on the row. Only the first line takes part in the alignment.

This generator refuses, each because the alternative compiles something wrong
or loses a reason:

  - a missing or unknown field, a family or product id declared twice, a value
    reused (a Component Member persists the value, so a reused one re-points
    every controller that stored it);
  - a product whose family is not declared, or a family's products split
    across the list (the manifest groups a family's rows under one banner);
  - a status other than supported or roadmap; a roadmap product that is
    confirmed on a droid or whose `included` is not 0 (it has no driver);
  - a confirmed product without a `confirmed_source`, or a source on one that
    is not confirmed: the header promises each confirmed row says where the
    claim comes from;
  - a `sheet` that is not a file under docs/spec-sheets/;
  - anything outside ASCII.

Staleness is the one thing this cannot catch, because it is what happens when
nobody runs it. tools/check_component_registry_generated_drift.py runs this
generator with its writes intercepted and byte-compares, and
`make check-action-drift` carries that check.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent


def rel(path):
    """Repo-relative where the path is in the tree, plain otherwise."""
    try:
        return str(Path(path).resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


PRODUCTS_PATH = ROOT / "docs" / "products.yaml"
SHEETS_DIR = ROOT / "docs" / "spec-sheets"
OUTPUT_PATH = ROOT / "include" / "component_registry.inc"
GENERATOR_NAME = rel(__file__)

FAMILY_FIELDS = {"id", "enumerator", "name", "member_key", "comment", "section"}
FAMILY_REQUIRED = {"id", "enumerator", "name", "member_key", "section"}
PRODUCT_FIELDS = {
    "value", "id", "name", "family", "protocol", "status", "confirmed_on_droid",
    "confirmed_source", "capabilities", "gate", "included", "sheet", "wiring_card", "notes",
}
PRODUCT_REQUIRED = PRODUCT_FIELDS - {"confirmed_source", "wiring_card"}
STATUSES = {"supported": "COMPONENT_STATUS_SUPPORTED", "roadmap": "COMPONENT_STATUS_ROADMAP"}
CONFIRMED = {True: "COMPONENT_CONFIRMED_ON_DROID", False: "COMPONENT_NOT_CONFIRMED_ON_DROID"}

RULE = "// " + "-" * 77
PART_OPEN = "PA_COMPONENT_PART("
CAPABILITIES_PER_LINE = 2

PREAMBLE = f"""\
// DO NOT EDIT MANUALLY. Generated by {GENERATOR_NAME} from
// {rel(PRODUCTS_PATH)}. Edit the YAML, then run the generator;
// `make check-action-drift` fails while the two disagree.
//
// Component Registry inventory (ADR 0042 as amended 2026-09-09; #303, #340).
//
// The single declaration of every Component Family and its members. Firmware
// tables, the identity manifest and the operator lineup all derive from these
// rows, so a product is added to docs/products.yaml and nowhere else. The
// content began as #303's resolved lineup (seven categories, twenty-one
// products, nine of them roadmap); the Radio Controller rows were redrawn as
// radios on #369.
//
// This file is an unguarded X-macro manifest, intentionally included
// repeatedly. Define BOTH PA_COMPONENT_CATEGORY and PA_COMPONENT_PART before
// including it -- define the one you do not need as empty rather than leaving
// it out, so a missing definition stays a hard error instead of silently
// dropping half the registry. Adding #pragma once here breaks the mechanism:
// include/component_registry.h expands this file five times in one translation
// unit with different macro definitions, and #pragma once would make every
// expansion after the first a no-op.
//
// -----------------------------------------------------------------------------
// PA_COMPONENT_CATEGORY(enumerator, id, name, member_key)
// -----------------------------------------------------------------------------
//   enumerator  the C++ enumerator for this Component Family
//   id          the stable token the JSON payload reports it under
//   name        the operator-visible category name
//   member_key  the NVS key holding this family's Component Member, or nullptr
//               where the family has no member setting. A member setting
//               exists ONLY where identity reports more than one selectable
//               member (GLOSSARY.md "Component Member"); the invariant is
//               asserted in test/test_native/test_component_registry, not
//               trusted to whoever edits this file.
//
// -----------------------------------------------------------------------------
// PA_COMPONENT_PART(value, id, name, category, protocol, status,
//                   confirmed_on_droid, capabilities, gate, included)
// -----------------------------------------------------------------------------
//   value         stable numeric id, unique across the whole registry. This is
//                 what a Component Member setting persists, so a value is never
//                 reused and never renumbered -- a renumber silently re-points
//                 every controller that already stored the old number. New rows
//                 take the next free value wherever they sit in the table.
//   id            the stable token the JSON payload reports it under
//   name          the operator-visible product name. It travels in the image on
//                 purpose: `make ota` and `make uploadfs` are separate steps, so
//                 a controller whose firmware is newer than its web assets must
//                 be able to name what it reports without help (ADR 0042).
//   category      a PA_COMPONENT_CATEGORY enumerator
//   protocol      the Component Protocol token firmware speaks to this product.
//                 One protocol commonly serves several products, and two rows
//                 sharing a token is the visible form of that -- `de_packet_serial`
//                 drives a Sabertooth under Foot Drive and a SyRen under Dome
//                 Rotation from one implementation (GLOSSARY.md "Component
//                 Protocol"). `none` is the Body Controller's: it hosts
//                 protoArtoo rather than being driven by it.
//   status        COMPONENT_STATUS_SUPPORTED (implemented and drivable) or
//                 COMPONENT_STATUS_ROADMAP (intended, not built). Two values,
//                 and "might" is deliberately not one of them (#303).
//   confirmed_on_droid
//                 COMPONENT_CONFIRMED_ON_DROID where the product has run on a
//                 real droid, COMPONENT_NOT_CONFIRMED_ON_DROID where it is
//                 built and drivable but has not yet (GLOSSARY.md "Confirmed on
//                 a Droid", #455). Evidence about a supported row, never a
//                 third status: a roadmap row has no driver to have run, so it
//                 cannot carry it (asserted in src/component_registry.cpp and
//                 reported by tools/check_component_registry_drift.py). A bench
//                 over USB is not a droid. Each confirmed row says where the
//                 claim comes from on the line above it - above, because a
//                 comment after the row's closing parenthesis breaks the
//                 readers that find a row's end by its line
//                 (test/playwright/_lib/fixture_routes.js). Confirming a
//                 product later is its `confirmed_on_droid` and
//                 `confirmed_source` in docs/products.yaml.
//   capabilities  what this product can be asked, as the family's own bitmask.
//                 Declared per part, not per family and not per protocol: two
//                 products on one protocol can genuinely differ in what they
//                 can be asked (ADR 0042). Sound (AudioDriver::AUDIO_CAP_*)
//                 and Foot Drive (DRIVE_CAP_*, include/drive_capabilities.h)
//                 are the families with a vocabulary today; every other row
//                 declares 0, which says "nothing to ask", not "unknown".
//   gate          the Board Capability Gate this part requires, as the name
//                 string the payload reports, or nullptr where it needs none.
//                 nullptr is universal -- the same meaning ActionEntry gives it
//                 (include/action_registry.h). This is the row's board
//                 applicability: what a board can be WIRED for, which is a
//                 different question from what this image carries.
//   included      does this image carry a driver for this part, as a 0/1
//                 compile-time expression. Derived here rather than declared
//                 anywhere else, and it is what "more than one selectable
//                 member" counts. A roadmap row is always literally 0: drivers
//                 are carried only for supported parts, so a row present with
//                 no driver is the normal way an unbuilt part exists rather
//                 than a defect (ADR 0042 amended). A row naming a gate
//                 consults that gate here -- the pairing is checked by
//                 test/test_tools/test_component_registry_drift.py.

#ifndef PA_COMPONENT_CATEGORY
  #error "Define PA_COMPONENT_CATEGORY before including this inventory"
#endif
#ifndef PA_COMPONENT_PART
  #error "Define PA_COMPONENT_PART before including this inventory"
#endif
"""


class RegistryError(Exception):
    """The registry cannot be generated; `problems` says why, one per line."""

    def __init__(self, problems):
        super().__init__("\n".join(problems))
        self.problems = problems


def load_products(path=None):
    """The YAML document, read and checked. Raises RegistryError."""
    path = path or PRODUCTS_PATH
    text = path.read_text(encoding="utf-8")
    problems = []
    if not text.isascii():
        line = next(n for n, row in enumerate(text.splitlines(), 1) if not row.isascii())
        problems.append(f"{rel(path)}:{line}: carries a character outside ASCII")
    document = yaml.safe_load(text)
    if not isinstance(document, dict):
        raise RegistryError([f"{rel(path)}: holds no mapping"])
    for key in ("categories_banner", "families", "products"):
        if key not in document:
            problems.append(f"{rel(path)}: missing top-level `{key}`")
    if problems:
        raise RegistryError(problems)

    families = document["families"]
    family_ids = []
    for position, family in enumerate(families):
        where = f"{rel(path)}: families[{position}]"
        if not isinstance(family, dict):
            problems.append(f"{where}: must be a mapping")
            continue
        where = f"{where} ({family.get('id')})"
        for key in sorted(set(family) - FAMILY_FIELDS):
            problems.append(f"{where}: unknown field `{key}`")
        for key in sorted(FAMILY_REQUIRED - set(family)):
            problems.append(f"{where}: missing field `{key}`")
        if family.get("id") in family_ids:
            problems.append(f"{where}: a second family with this id")
        family_ids.append(family.get("id"))

    products = document["products"]
    seen_ids, seen_values, family_order = set(), set(), []
    for position, product in enumerate(products):
        where = f"{rel(path)}: products[{position}]"
        if not isinstance(product, dict):
            problems.append(f"{where}: must be a mapping")
            continue
        where = f"{where} ({product.get('id')})"
        before = len(problems)
        for key in sorted(set(product) - PRODUCT_FIELDS):
            problems.append(f"{where}: unknown field `{key}`")
        for key in sorted(PRODUCT_REQUIRED - set(product)):
            problems.append(f"{where}: missing field `{key}`")
        if len(problems) > before:
            continue
        if product["id"] in seen_ids:
            problems.append(f"{where}: a second product with this id")
        seen_ids.add(product["id"])
        if not isinstance(product["value"], int) or product["value"] in seen_values:
            problems.append(f"{where}: `value` must be a number no other product uses")
        seen_values.add(product["value"])
        if product["family"] not in family_ids:
            problems.append(f"{where}: family {product['family']!r} is not declared")
        if not family_order or family_order[-1] != product["family"]:
            if product["family"] in family_order:
                problems.append(f"{where}: {product['family']!r}'s products must be listed together")
            family_order.append(product["family"])
        if product["status"] not in STATUSES:
            problems.append(f"{where}: `status` must be one of {', '.join(STATUSES)}")
        if not isinstance(product["confirmed_on_droid"], bool):
            problems.append(f"{where}: `confirmed_on_droid` must be true or false")
        elif product["confirmed_on_droid"] != ("confirmed_source" in product):
            problems.append(
                f"{where}: a product confirmed on a droid says where that comes from in "
                "`confirmed_source`, and only such a product has one"
            )
        if product["status"] == "roadmap" and (product["confirmed_on_droid"] or product["included"] != 0):
            problems.append(f"{where}: a roadmap product has no driver: not confirmed, `included: 0`")
        if not isinstance(product["capabilities"], list):
            problems.append(f"{where}: `capabilities` must be a list, [] for none")
        if product["sheet"] is not None and not (SHEETS_DIR / str(product["sheet"])).is_file():
            problems.append(f"{where}: `sheet` {product['sheet']!r} is no file in {rel(SHEETS_DIR)}/")
    if family_order != [family for family in family_ids if family in family_order]:
        problems.append(f"{rel(path)}: products must follow the families' order")
    if problems:
        raise RegistryError(problems)
    return document


def comment_lines(text):
    """A block of prose as `//` lines, a blank line kept as a bare `//`."""
    return [f"// {line}" if line else "//" for line in text.rstrip("\n").split("\n")]


def c_string(value):
    return "nullptr" if value is None else f'"{value}"'


def aligned(rows):
    """Each row's cells joined with every column but its last padded to the
    widest cell in that column across `rows`. A row may be shorter than the
    rest; it is padded only in the columns it has before its last."""
    widths = {}
    for row in rows:
        for column, cell in enumerate(row[:-1]):
            widths[column] = max(widths.get(column, 0), len(cell))
    return [
        "".join(cell.ljust(widths[column]) + " " for column, cell in enumerate(row[:-1])) + row[-1]
        for row in rows
    ]


def category_rows(families):
    rows = aligned([
        [f"{family['enumerator']},", f"{c_string(family['id'])},", f"{c_string(family['name'])},",
         f"{c_string(family['member_key'])})"]
        for family in families
    ])
    lines = []
    for family, row in zip(families, rows):
        if family.get("comment"):
            lines += comment_lines(family["comment"])
        lines.append(f"PA_COMPONENT_CATEGORY({row}")
    return lines


def product_rows(family, products):
    """A family's rows. Every row's first line is aligned with its family's."""
    firsts = []
    for product in products:
        head = [
            f"{product['value']:2d},",
            f"{c_string(product['id'])},",
            f"{c_string(product['name'])},",
            f"{family['enumerator']},",
            f"{c_string(product['protocol'])},",
            f"{STATUSES[product['status']]},",
            f"{CONFIRMED[product['confirmed_on_droid']]},",
        ]
        if not product["capabilities"]:
            # The last three cells are not aligned: they close the row.
            head.append(f"0, {c_string(product['gate'])}, {product['included']})")
        firsts.append(head)
    lines = []
    for product, first in zip(products, aligned(firsts)):
        if product.get("confirmed_source"):
            lines.append(f"// Confirmed on a droid: {product['confirmed_source']}")
        lines.append(PART_OPEN + first)
        if product["capabilities"]:
            indent = " " * len(PART_OPEN)
            bits = product["capabilities"]
            chunks = [bits[i:i + CAPABILITIES_PER_LINE] for i in range(0, len(bits), CAPABILITIES_PER_LINE)]
            for position, chunk in enumerate(chunks):
                end = "," if position == len(chunks) - 1 else " |"
                lines.append(indent + " | ".join(chunk) + end)
            lines.append(f"{indent}{c_string(product['gate'])}, {product['included']})")
    return lines


def render(document):
    """The manifest as text."""
    families = document["families"]
    lines = [PREAMBLE.rstrip("\n"), "", RULE, f"// {document['categories_banner']}", RULE]
    lines += category_rows(families)
    for family in families:
        members = [product for product in document["products"] if product["family"] == family["id"]]
        lines += ["", RULE, *comment_lines(family["section"]), RULE]
        lines += product_rows(family, members)
    return "\n".join(lines) + "\n"


def generate(quiet=False, products_path=None, output_path=None):
    """Write the manifest and return its text. Raises RegistryError."""
    document = load_products(products_path)
    text = render(document)
    output_path = output_path or OUTPUT_PATH
    output_path.write_text(text, encoding="utf-8")
    if not quiet:
        print(
            f"Generated {rel(output_path)} ({len(document['families'])} families, "
            f"{len(document['products'])} products)"
        )
    return text


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--quiet", action="store_true", help="print nothing on success")
    args = parser.parse_args(argv)
    try:
        generate(quiet=args.quiet)
    except RegistryError as error:
        print(f"{rel(PRODUCTS_PATH)} cannot be generated:", file=sys.stderr)
        for problem in error.problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
